# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f7fb13500940a485d05d18fce715e709bdfa5ac1c45e1e7936648e2272337cae0ca666dd0405649cf99c001bbe57a0a5c5e32e63915ba1ecb39d8dc019bcad

test:
  secret_key_base: f779abe70966ec3ef1dfa708df7d1a13528f6a7caddcd6620a0ed6a1db770ab794e68649bb1afdf63e380a832f777f9e3f56431e505ff1828bd1a7a27f4c8682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
